--- 
run_list: 
- tvdinner
tvd: 
  class: Gollum
  name: gollum
  author: Tom Bombadil
  email: amanibhavam@destructuring.org
  summary: Gollum service
  description: Gollum unicorn managed by runit
  homepage: http://destructuring.org/tvd-gollum
  git_url: https://github.com/destructuring/tvd-gollum
