#!/bin/bash

#/ NAME
#/     sv-gollum-run -- run gollum under unicorn
#/
#/ SYNOPSIS
#/     ./run

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")" && pwd -P)"

# entry point
function main {
  exec bundle exec unicorn "$(cat $shome/env/RELEASE_DIR)/config.ru"
}

# pass arguments to entry point
main "$@"
